name: xchain_utils
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/CW-75/xchain-dart.git
publish_to: none
environment:
  sdk: ^3.5.4

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dependencies: 
  bignumbers: 
    git:
      url: "https://github.com/CW-75/bignumbers_dart.git"
      ref: "main"
  http: ^1.5.0
resolution: workspace

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
